config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  
  resources :sessions, only: :create 
  resources :microposts, only: [:create,:destroy]
  resources :relationships, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end

  

  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :user_id ,presence: true
  validates :content ,presence: true , length:{maximum: 240}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, length: { maximum: 50, minimum: 2}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { mximum: 50, minimum: 4 },
                                    format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: true }
  
  validates :password, length: { minimum: 6 }

  has_many :microposts, dependent: :destroy

  has_many :active_relationships, foreign_key: "follower_id",
                                  class_name: 'Relationship',
                                  dependent: :destroy
  has_many :followed_users, through: :active_relationships, source: :followed

  has_many :passive_relationships, foreign_key: "followed_id",
                                   class_name: "Relationship",
                                   dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  def feed
      Micropost.where("user_id = ?", id)
  end

  #returns true if the current user is following the other user
  def following?(other_user)
      active_relationships.find_by(followed_id: other_user.id)
  end
  # follows a users
  def follow(other_user)
      active_relationships.create!(followed_id: other_user.id)
  end
  # unfollows a user
  def unfollow(other_user)
      active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def logged_in_user
    unless logged_in?
      flash[:info] = "Please login first"
      redirect_to login_url
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only:[:create,:destroy]
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!!"
    else
      flash[:danger] = "Please input content"
    end
    redirect_back(fallback_location: request.referer)
  end

  def destroy
    Micropost.find(params[:id]).destroy
    flash[:success] = "Successfully deleted"
    redirect_back(fallback_location: request.referer)
  end
  private
  def micropost_params
    params.require(:micropost).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if logged_in?
    @user = current_user
    @micropost = current_user.microposts.build
    @feed_item = current_user.feed.paginate(page: params[:page],per_page:12)
    end
  end

  def about
  end

  def contact
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html{ redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html{ redirect_to @user }
      format.js
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email:params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      flash[:success] = "Successfully logged in !!"
      redirect_to root_url
    else
    flash[:danger] = " Invalid Credentials"
      redirect_to login_url
    end
  end

  def destroy
      log_out
      flash[:success] = "Successfully logged out."
      redirect_to root_url
  end

end

 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: [:index ,:new, :create,:destroy,:following,:followers]
  before_action :correct_user, only: :edit

  def index
    # @users = User.all
    @users = User.paginate(page: params[:page], per_page: 10 )
  end

  def show
    @user = User.find(params[:id])
    @micropost = current_user.microposts.build if @user == current_user
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 12 )
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Successfully Created an Account!! "
      redirect_to root_url
    else
        render 'new'
      
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated!!"
      redirect_to root_url
    else
      render 'edit'
    end
  end


  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url
 end

 def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page],per_page:5)
    @all_users = @user.followed_users
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page],per_page:5)
    @all_users = @user.followers
    render 'show_follow'
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
    
  end
  def correct_user
    user = User.find(params[:id])
     if user != current_user
      flash[:danger] = "You're not authorized."
      redirect_to root_url
     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    # Logs in the given user.
    def log_in(user)
      session[:user_id] = user.id
    end

    # Returns the current logged-in user (if any).
    def current_user
      User.find_by(id: session[:user_id])
    end

    def current_user?(user)
      current_user == user
    end

    # checks if the user is logged in or not
    def logged_in?
      !current_user.nil?
    end

    # Logs out the current user.
    def log_out
      session.delete(:user_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
   # Returns the Gravatar (http://gravatar.com/) for the given user.
   def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_alart.erb
<% if flash.any? %>
  <% flash.each do |type, msg|%>
     <div class="mt-4 alert alert-<%=type%> alert-dismissable fade show" role="alert">
            <strong><%=msg%></strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          
        </div>
   <% end %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
<div class="container">
      <a class="navbar-brand text-white" href="/">Awesome Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
           <%= link_to raw("Home<span class='sr-only'>(current)</span>"), root_url, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
           <%= link_to "About Us", pages_about_url, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
           <%= link_to "Contact", pages_contact_url, class: "nav-link text-white" %>
          </li>
          <li class="nav-item dropdown">

        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
              <%= link_to current_user.name , user_path(current_user), class: "dropdown-item"%>
              <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item"%>
              <%= link_to "Users", users_path, class: "dropdown-item"%>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", logout_path, class: "dropdown-item"%>
          <% else %>
              <%= link_to "Sign Up", signup_path, class: "dropdown-item"%>
              <div class="dropdown-divider"></div>
              <%= link_to "Login", login_path, class: "dropdown-item"%>
          <% end %>
        </div>
      </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> |AwesomeBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
    
  <body>
  <%= render "layouts/header" %>
    <div class="container">
    <%= render "layouts/alart" %>
      <%= yield %>
    </div>
    
  </body>

</html>

app/views/microposts/_micropost.html.erb
<div class="card mb-3 w-100">
<div class="row">
<div class="col-2">
<%= link_to gravatar_for(micropost.user ,size:52), user_path(micropost.user)%>
</div>
  <div class="col-10">
    <h5 class="card-title">
      <%= link_to micropost.user.name , micropost.user%>
    </h5>
    <p class="card-text"><%= micropost.content%></p>
    <p class="card-text">
      <small class="text-muted">
      <%= time_ago_in_words(micropost.created_at)%>
      </small>
      <% if current_user == @user %>-
        <%= link_to 'Delete', micropost, method: :delete, data: { confirm: "Are you sure?" } , 
        title: micropost.content,
        class:"text-danger" %>
      <% end %>
    </p>
  </div>
</div>
</div>

app/views/pages/about.html.erb
<% provide(:title,"About")%>

<div class="jumbotron">
  <h1 class="display-4">About us</h1>
  <p class="lead">Takumi Hamamoto</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>

app/views/pages/contact.html.erb
<% provide(:title,"Contact us")%>
<div class="jumbotron">
  <h1 class="display-4">Contact me</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>

app/views/pages/home.html.erb
<% provide(:title,"Home")%>
<% if logged_in?%>
  <div class="row">
    <div class="col-3">
      <section>
        <%= render "shared/user_info"%>
      </section>
      <section>
        <%= render "shared/micropost_form"%>
      </section>
    </div>
    <div class="col-9">
      <div class="card">
        <div class="card-title">
          <h1>microposts</h1>
        </div>
        <div class="card-body">
          <%= render "shared/feed"%>
        </div>
      </div>
    </div>
  </div>

<% else %>

<div class="jumbotron">
  <h1 class="display-4">Awesome Blog</h1>
  <p class="lead">Welcome to AwesomeBlog</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>

<% end %>

app/views/relationships/create.js.erb
 //views/relationships/create.js.erb
$("#follow_form").html("<%=escape_javascript(render('users/unfollow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/relationships/destory.js.erb
// views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/shared/_error_messages.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
        <ul>
            <% object.errors.full_messages.each do |msg|%>
                <li> <%= msg %> </li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_item.any? %>
  <ol class="microposts-items">
    <%= render partial: "shared/feed_item",collection: @feed_item %>
  </ol>
    <%= will_paginate @feed_item %>
<% end %>

app/views/shared/_feed_item.html.erb
<div class="card my-3 w-100">
  <div class="row">
    <div class="col-2">
      <%= link_to gravatar_for(feed_item.user ,size:52), user_path(feed_item.user)%>
</div>
  <div class="col-10">
    <h5 class="card-title">
      <%= link_to feed_item.user.name , feed_item.user%>
    </h5>
    <p class="card-text"><%= feed_item.content%></p>
    <p class="card-text">
      <small class="text-muted">
      <%= time_ago_in_words(feed_item.created_at)%>
      </small>
    </p>
  </div>
</div>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true ) do |f|%>
<div class="form-group">
  <%= f.text_area :content , size: "20x5" , class:'form-control', placefolder: "Share you thoughts.."%>
</div>
<%= f.submit "Post",class: "btn btn-primary w-100 my-2" %>
<%end%>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user)%>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    Following
  </a>
  <a href="<%= followers_user_path(@user)%>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(@user,size:52),@user%>
  <h1>
    <%= @user.name%>
  </h1>
  <span>
    <%= pluralize(@user.microposts.count,"Micropost")%>
  </span>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build,remote: true) do |f| %>
<div><%= hidden_field_tag :followed_id,@user.id %></div>
<%= f.submit "Follow", class:"btn btn-large btn-primary"%>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user)%>
  <div id="follow_form">
    <% if current_user.following?(@user)%>
      <%= render 'unfollow'%>
    <% else%>
      <%= render 'follow'%>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="mb-3">
        <%= f.text_field :name, class: "form-control", placeholder: "Name"%>
    </div>
    <div class="mb-3">
        <%= f.email_field :email, class: "form-control", placeholder: "Email"%>
    </div>
    <div class="mb-3">
        <%= f.password_field :password, class: "form-control", placeholder: "Password"%>
    </div>
    <div class="mb-3">
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation"%>
    </div>
    <%= f.submit btn_msg, class: "btn btn-success"%>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
                                                      html:{ method: :delete },
                                                      remote: true) do |f| %>
<%= f.submit "Unfollow", class:"btn btn-large btn-secondary"%>
<% end %>

app/views/users/_user.html.erb
<li class="col-12 my-4">
  <%= link_to gravatar_for(user),user%>
  <span class="user">
    <%= link_to user.name, user%>
  </span>
</li>

app/views/users/edit.html.erb
<%= provide(:title,"Edit Profile")%>
<div class="col-4">
  <h1 class="text-center mt-4">Edit Profile</h1>
  <%= render 'form', btn_msg:"Update Profile"%>
</div>

app/views/users/index.html.erb
<%= provide(:title,"Users list")%>
<div class="row">
  <div class="col-12">
    <div class="container my-3">
      <h1 class="texr-center">List of Users</h1>
      <%= will_paginate %>
        <ul class="users">
          <% @users.each do |user|%>
          <li class="my-3">
            <%= gravatar_for user ,size:52%>
            <%= link_to user.name, user%>
            <% if current_user ==user %> -
            <%= link_to 'Delete', user_path(user),
            method: :delete,
            data: { confirm: "Are you sure?" },
            class:"text-danger"
            %>
            <% end %>
          </li>
          <% end %>
        </ul>
      <%= will_paginate %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= provide(:title,"Edit Profile")%>
<div class="col-4">
  <h1 class="text-center mt-4">Register Profile</h1>
  <%= render 'form', btn_msg: "Submit"%>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.name)%>
<div class="row pt-5">
  <div class="col-4">
    <div class="card">
      <div class="card-header">
        User Infomation
      </div>
      
      <div class="card-body text-center">
        <%= gravatar_for @user, size:52 %>
        <h5><%=@user.name %></h5>
        <p><%= @user.email%></p>

        <hr>
      <section>
        <%= render 'follow_form' if logged_in? %>
        <%= render 'shared/stats' %>
      </section>

        <% if @user == current_user %>
          <div class="card-footer">
            <%= render "shared/micropost_form"%>
          </div>
        <% end%>
      </div>
    </div>
  </div>
  <div class="col-8">
    <div class="card">
      <div class="card-header">
        Activity Feeds
      </div>
      <div class="card-body">
        <% if @microposts.any? %>
          <%= render @microposts %>
          <div class="justify-content-center mt-4">
            <%= will_paginate @microposts %>
          </div>
        <% else %>
          <h4 class="text-center"> No posts found</h4>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title ,@title) %>
  <div class="row">
    <div class="col-4">
      <section class="user_info">
        <%= gravatar_for @user %>
          <h1> <%= @user.name %> </h1>
          <span> <%= link_to "view profile", @user %> </span>
          <span> <b>Microposts:</b> <%= @user.microposts.count %> </span>
        </section>
        <section class="stats">
          <%= render 'shared/stats' %>
            <% if @all_users.any? %>
              <div class="user_avatars">
                 <% @all_users.each do |user| %>
                 <%= link_to gravatar_for(user, size: 30), user %>
                 <% end %>
              </div>
            <% end %>
      </section>
    </div>
    <div class="col-8">
      <h3><%= @title%></h3>
      <% if @users.any?%>
        <%@users.each do |user|%>
            <ul class="user_follow">
              <%= render user%>
            </ul>
        <% end%>
        <%= will_paginate @users%>  
      <%end%>
    </div>
  </div>